### ISSUE TITLE
P360-Search-Nested Link for Date field -Fairview

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#134] opened 2024-09-26 09:14 UTC
**Describe the bug**
P360-The nested link fetching incorrect results for date field

**To Reproduce**
1.Create a search with Datetime search result and another search with date in the search form
2. Establish nested link between both date columns
3. Fetching improper results through nested link. Please refer attached word doc for screenshots
(Note:Nested link yield expected results for string datatype)

**Expected behavior**
Nested link should fetch proper results with Date datatype

**Screenshots**
[error_nested_link.docx](https://github.com/user-attachments/files/17145828/error_nested_link.docx)

**Additional context**
Build no :
Region :
Client :

**Comment by kilam005** [comment] 2024-09-27 05:36
@ThulasiP3 
provide the metadata and the search export file for both the main and nested search

**Comment by kilam005** [comment] 2024-09-27 07:20
Issue was demoed and details were observed.
Actual issue is: When multiple data goes in link, the link operation is not functioning properly.

Code fix needed.

**Comment by Thilak-Saravanan** [comment] 2024-09-27 14:57
`RCA`
Payload mapping was not handled for date field, also when more than one link columns are configured due to code glitch only the latest column was considers as a linkable column.

`Fix details`
Payload mapping has been corrected, Multi column link issue has been resolved by correcting the code glitch.

**Comment by VikramSelvadurai** [comment] 2024-09-27 15:16
![image](https://github.com/user-attachments/assets/02fb2a93-e858-4d58-95cc-412ff47e8cae)
![image](https://github.com/user-attachments/assets/6a049b41-5c3a-47a7-b255-b04750ee863c)

**Comment by VikramSelvadurai** [comment] 2024-09-28 08:21
Sever SS: 
![image](https://github.com/user-attachments/assets/175879d0-ca7d-4e08-a3b4-e302bea11560)
![image](https://github.com/user-attachments/assets/225b866b-7bdd-471d-a67c-d07b2508e461)

**Comment by kilam005** [comment] 2024-09-28 08:38
@P3IND0167 if this is tested please marks as verified and tag it as Awaiting release

**Comment by P3IND0167** [comment] 2024-09-28 10:31
Verified in Test server , adding screenshots

![image](https://github.com/user-attachments/assets/2259fcb0-96f2-4fba-a20c-942fd6ac4e99)
![image](https://github.com/user-attachments/assets/c765dfef-e7ff-4a1a-b627-4e4a875e7b67)
![image](https://github.com/user-attachments/assets/58c9cef6-24a0-44e3-aa93-a92fe1245d90)

**Comment by kilam005** [comment] 2024-10-05 00:32
@ThulasiP3 

The issue is addressed in the latest build (P360 v2024.09.45555) verified by testing team also. Please check above comments.
Link to the build shared on email on Sep 30.
If you have not received the email, kindly reach out to support team for build details.

Please udpate your environment with this build and verify.

**Comment by kilam005** [comment] 2024-10-10 16:45
@ThulasiP3 

Its been more than 10 days since we gave the release.
Please validate the fix and provide a closure.
if no repsonse / concerns is received  by 18th October this issue will be auto closed taking testing team's verifiied confirmation

**Comment by ThulasiP3** [comment] 2024-10-14 05:54
Hi,

Requested for deployment in Fairview .We will validate and post back ASAP.

Thanks,
Thulasi.

**Comment by kilam005** [comment] 2024-10-14 06:05
@ThulasiP3 
For P360 we dont own the region and we never deploy.
The details about the instalation and upgrade are provided with the package.
Please update, check and confirm and provide the closure.

Like previous mentioned if no closure or concern is raised before 18th October, this will get auto closed

**Comment by kilam005** [comment] 2024-10-14 06:14
Closed by mistake. opening it up.

**Comment by ThulasiP3** [comment] 2024-10-18 06:52
Issue still persists in the build given..(v2024.09.45555)

![image](https://github.com/user-attachments/assets/ab2ea3e5-c51c-4f48-9455-2225b5c825d9)
![image](https://github.com/user-attachments/assets/ee5fc6ed-5ce1-4176-bf85-fc301bf73bd5)
![image](https://github.com/user-attachments/assets/27d1c77c-8b56-4059-a98a-54a9415644bb)

**Comment by kilam005** [comment] 2024-10-18 07:18
@Udhayanila8 / @Thilak-Saravanan  / @VikramSelvadurai 
please check this again and confirm.

Also discuss with Thulasi and find out the execution steps.

**Comment by Thilak-Saravanan** [comment] 2024-10-18 07:37
@kilam005 
Validated this with Ramya, It was an cache issue on UI. On refresh they were able to validate the fix.

@ThulasiP3 can you confirm on this once?

**Comment by ThulasiP3** [comment] 2024-10-18 07:39
Cleared the cache and retested. Now Nested link works for multiple columns and date field.Thanks!!

**Comment by kilam005** [comment] 2024-10-18 09:04
Based on the above comment closing the issue

**Closed by kilam005** 2024-10-18 09:04 UTC
Labels: bug, Verified, Awaiting closure, P360, P360-Search, 18th October - auto close
