### ISSUE TITLE
P360-Info Template -Search Export unavailable-Fairview

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#130] opened 2024-09-25 02:47 UTC
**Describe the bug**
P360 Info Template does not have search export configuration available

**To Reproduce**
1.Create a search using info template 
2.Enable export on result column. No export configuration through permission tab on search available
3.Run search through patient lookup .Unable to see export option

**Expected behavior**
Export feature available on search patient lookup for info template

**Screenshots**

**Additional context**
Build no :
Region :
Client :

**Comment by kilam005** [comment] 2024-09-25 05:26
@VikramSelvadurai 
i believe this is already fixed.

Can you please add the screen shot of the fixes and also confirm if this is Yet to be release or if already released, in which version it was included

**Comment by VikramSelvadurai** [comment] 2024-09-25 13:54
**RCA**
Search Permission tab not enable to INFO_TEMPLATE
**Fix Details** 
enable permission tab with some conditions 

@kilam005 this will release in upcomming build 

initial page user can't able to change the user permission, its disable mode for INFO_TEMPLATE alone
in Permission tab ,  **Grant Access** is always enabled for all groups, user can't  modify access so we make this field disabled **Grant Export**  there is no change with this , its working as other tempalte , here user can grant access for export alone  

Local SS: 

![image](https://github.com/user-attachments/assets/c4335fd4-3c00-454a-8346-4617f49df398)
![image](https://github.com/user-attachments/assets/8b8eebc6-211b-43b2-8fcb-c27fb63c4d0d)
![image](https://github.com/user-attachments/assets/8c5ff5ca-5703-471f-901e-835266f8aaa7)
![image](https://github.com/user-attachments/assets/4881f920-b5bf-4349-9923-7945e93feb52)

if u need enable the export icon, u have enable Grand Export access

![image](https://github.com/user-attachments/assets/8ecf57a1-9839-4369-8e7c-875c51a396f2)
![image](https://github.com/user-attachments/assets/3a34c2c7-1fea-4269-87cf-a3485b8390e4)
![image](https://github.com/user-attachments/assets/09fbd4dc-bc3a-4da3-a8b6-6e0810002b81)

**Comment by VikramSelvadurai** [comment] 2024-09-27 10:19
Server SS: 
![image](https://github.com/user-attachments/assets/deafe3ec-1419-4c41-8350-d24d69504163)
![image](https://github.com/user-attachments/assets/29265d1e-a385-413c-968e-0924a2b61d88)
![image](https://github.com/user-attachments/assets/45f81f79-8e9c-4ca4-85d6-805e415ca5f9)
![image](https://github.com/user-attachments/assets/247748e5-1244-4111-941f-98684426d049)
![image](https://github.com/user-attachments/assets/09990923-bbd7-42cf-a4c6-3fe570fb75ac)

**Comment by kilam005** [comment] 2024-09-28 08:39
@P3IND0167 
once tested and confirmed to be working fine, mark it as verified and add the Awaiting release tag

**Comment by P3IND0167** [comment] 2024-09-28 09:30
Verified in Test server adding screenshots

**Case - Without Providing Grant export**
![image](https://github.com/user-attachments/assets/12629093-9ca9-4a58-9c83-f141160ffb09)
![image](https://github.com/user-attachments/assets/33e4019b-dd26-4275-a363-9c3f83485e17)
![image](https://github.com/user-attachments/assets/6b56f855-059c-4826-b899-d12c4b19aede)
![image](https://github.com/user-attachments/assets/006c6505-2193-49cd-bc8e-845a4ba5024a)
![image](https://github.com/user-attachments/assets/b4175543-d03f-4f83-8be7-aaea5ed62f0b)

**Case - with Providing Grant export**
![image](https://github.com/user-attachments/assets/a78353ba-204f-4447-8006-1db92a3865a0)
![image](https://github.com/user-attachments/assets/cc1a8193-074c-4414-ad8c-f3c085b04c96)

**Case- Checking user can export Successfully**
![image](https://github.com/user-attachments/assets/a87c1df8-3b50-45f0-aca6-d84bb0b53ed0)
![image](https://github.com/user-attachments/assets/941d0f80-ce3b-4ba8-9970-f0ec729e98c5)
![image](https://github.com/user-attachments/assets/3ebbf1fd-d836-4cca-b5c2-68fbbea98125)

**Comment by kilam005** [comment] 2024-10-05 00:32
@ThulasiP3 

The issue is addressed in the latest build (P360 v2024.09.45555) verified by testing team also. Please check above comments.
Link to the build shared on email on Sep 30.
If you have not received the email, kindly reach out to support team for build details.

Please udpate your environment with this build and verify.

**Comment by kilam005** [comment] 2024-10-10 16:45
@ThulasiP3 
Its been more than 10 days since we gave the release.
Please validate the fix and provide a closure.
if no repsonse / concerns is received  by 18th October this issue will be auto closed taking testing team's verifiied confirmation

**Comment by ThulasiP3** [comment] 2024-10-14 05:54
Hi,

Requested for deployment in Fairview .We will validate and post back ASAP.

Thanks,
Thulasi.

**Comment by kilam005** [comment] 2024-10-14 06:07
@ThulasiP3 
For P360 we dont own the region and we never deploy.
The details about the instalation and upgrade are provided with the package.
Please update, check and confirm and provide the closure.

Like previous mentioned if no closure or concern is raised before 18th October, this will get auto closed

**Comment by kilam005** [comment] 2024-10-20 04:30
@ThulasiP3 
Reminder: Issue will be autoclosed if no action is taken on 21st Oct

**Comment by ThulasiP3** [comment] 2024-10-21 09:55
Build verified...Issue resolved.For info template ,the export option is available in patient lookup

**Comment by kilam005** [comment] 2024-10-22 02:54
Closing based on above comment

**Closed by kilam005** 2024-10-22 02:54 UTC
Labels: bug, Verified, Info Provided, Awaiting closure, P360, P360-Search, 18th October - auto close
