### ISSUE TITLE
ADS-Search - Failure on Unstructured Data retrieval - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#154] opened 2024-11-07 07:43 UTC
**Describe the bug**
1.For ABB we are extracting  reports and storing it in a single table called REPORTSVESE.
In this case , i have extracted two reports  OP0058P2,INSPECTN in a single extraction entity job.
These reports will be stored in a single table called REPORTSVESE while extraction.
Each reports will have the respective blob content and it will be stored in the blobs folder.
The below is the extracted path for this two reports:
![image](https://github.com/user-attachments/assets/b4e8ecdc-9101-489a-a3a1-835a191fdb04)

The DATA folder consists the Schema Name MOBIUS_DBO
![image](https://github.com/user-attachments/assets/891b19b6-cea4-4850-9273-c6125e918703)

Here there will be one table called REPORTSVESE
![image](https://github.com/user-attachments/assets/f4615383-30c7-461e-af9b-fbc29647df70)

Here there will be two parquet files for each of the reports Op0058P2,INSPECTN in the REPORTSVESE table and there will be blob folder where the blobs of these two reports will be stored in respective folder name,
![image](https://github.com/user-attachments/assets/d9a221e6-5f02-4e45-a265-706ef84f2625)

Blob Folder:
![image](https://github.com/user-attachments/assets/ea0c288e-e1b1-47aa-8540-9ec970ddc779)
Blobs for the report OP0058P2:
![image](https://github.com/user-attachments/assets/2969e7ae-91a3-45db-be13-ce598fb39ec6)
Blobs for the report INSPECTN:
![image](https://github.com/user-attachments/assets/91e6b540-5b32-490b-b17b-acb7343da336)

After that  i move the extracted file to s3 and then ingest in ADS.
While ingesting i can able to see the the ingestion is successfully completed.
while i querying these two reports from the tabel REPORTSVESE and view the result, for one of the report i can able to view the blob and for other report im unable to view it.

this is the screenshot for the report for which the blob content is able to view:
REPORT_NAME:OPOO58P2
![image](https://github.com/user-attachments/assets/61501822-5d2c-40bd-93e2-2e440d46d899)

The is the screenshot for the report im unable to view:
REPORT_NAME:INSPECTN
![image](https://github.com/user-attachments/assets/09c96aef-a62d-44c2-9969-b27f68d260ab).

Then i tried extracting only one report in a single extraction entity, means the REPORTSVESE table will have only the data for one report along with its respective blob content . After ingesting it into ADS , i can able to view the blob content.

When i extracting more than 1 report in a single extraction entity, the blobs are getting extracted successfully.After that  ingesting it  into ADS im facing this issue.

**Additional context**
Build no :2024.09.45542_P3
Region :https://dev.ads-platform3.elis.abb.com/metadata/a3f70340-91d7-41bb-bce6-c250b234ee3f
Client :ABB

**Comment by abirami1994** [comment] 2024-11-13 07:03
@kilam005 The fix was merged yesterday.
@Udhayanila8 Need to verify this.

**Comment by Udhayanila8** [comment] 2024-11-13 07:32
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4_**

Unable to view blob in data and search areas, so reopen this issue.
Data set
3 parquet files and inside blob folder three blob folder available
![image](https://github.com/user-attachments/assets/e661745f-a000-47f6-b9ad-22093534462b)
![image](https://github.com/user-attachments/assets/67eaa2e0-2e6a-4c81-bea1-0039726c139d)
Inside the blob folder the blob files are
![image](https://github.com/user-attachments/assets/f2c7d35c-ba26-47c9-8012-98ed3a1f3bf2)
Data ingested for blob 
![image](https://github.com/user-attachments/assets/e61584ce-062d-4aae-9643-52dd329daf2e)
But in data page and search page unable to view the blob data
![image](https://github.com/user-attachments/assets/2394cda3-b254-49a3-97af-101464dfd056)
![image](https://github.com/user-attachments/assets/27716133-8a1b-47ed-aecf-32441413407a)

**Comment by dinesh-p3** [comment] 2024-11-13 10:22
`RCA`
We added the necessary Tomcat configuration to address the clickjacking issue identified in the penetration test. The **antiClickJackingOption** was initially set to **DENY**. However, this prevented the blob from being displayed, as the UI relies on an iframe to render the blob

`Fix`
The **antiClickJackingOption** was changed to **SAMEORIGIN** to allow the iframe to display content from the same origin.

**Comment by dinesh-p3** [comment] 2024-11-13 10:22
@Udhayanila8  please verify and let us know

**Comment by Udhayanila8** [comment] 2024-11-13 10:56
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4_**

The above mentioned issue is working fine, able to view some blob files
![image](https://github.com/user-attachments/assets/9a839603-1d00-4057-8714-2b7a8f17609d)
All 3 folders blobs got ingested
![image](https://github.com/user-attachments/assets/21e55777-dbef-4040-b2dd-a5a3f6be4715)
But had some changes in the parquet data,
Still issue is replicated, while clicking blob file issue still replicated
![image](https://github.com/user-attachments/assets/d530d147-f791-4615-84bb-3c2dcf34defc)

**Issue replication steps**
1. Data should have 3 parquet file and 3 blob folders,
2. inside all blob folders should have pdf blob file.
3. open the 2nd parquet file, I'm choosing KU0016 data and edit the data, 
4. change the attachment name, and enter the wrong name which is not in the blob folder,
5. Trigger ingestion using the edited parquet file.
6. create basic search 
7. give the payload (KU0016 ), blob will be showed.
8. click the blob 

Once click the blob issue will replicated.

**Comment by abirami1994** [comment] 2024-11-13 13:03
@Udhayanila8   the issue occurred coz some data were not moved from stagging stage during ingestion. The scenario above mentioned occurred because the input parquet file has invalid value in the attachment column(non-existant file) .Can u please open this as a separate issue

**Comment by kilam005** [comment] 2024-11-13 13:59
@Udhayanila8 
The reason for RO is not right. 
The reason you have indicated is a different issue and should be tracked seperately.

Close this if the main reason is fixed and open a new issue for the reason you have indicated to mark this as re-open.

**Comment by Udhayanila8** [comment] 2024-11-13 16:22
@kilam005, 
In the above screenshot(Global Query Editor) added by @AshsubM , we could note the error in the tooltip while clicking the blob. The same error can be indicated on the search result page (Refer to the attached screenshot) but on a different scenario but the blob got ingested without any error (Refer to the replication steps). 

Due to this, we are unable to provide closure for the issue until the replicated issue is resolved.

**Comment by kilam005** [comment] 2024-11-14 04:32
There are 2 cases
1) the issue was opened for file retrieval.
2) negatiive test case : File was forcefully removed to track ingestion error marking.

Both issues are valid.
My expectaion is to track both as two sperate issues so that next time we have to do regression or sanity we'll have a hold to what all checks must be enforced..
If you track it to an existing issue (though it is indirectly related), we'll not have visibility.

**Comment by Udhayanila8** [comment] 2024-11-22 06:27
For the above mentioned new test case issue has been tracked in the following issue link https://github.com/P3-Core-Dev-Team/ADS_BE/issues/3406.

**Comment by AshsubM** [comment] 2024-11-22 10:05
I have extracted 10 Reports in a single extraction entity and ingested the data in ADS, now able to view the blobs for each report without any issues.
OP0058P2:
![image](https://github.com/user-attachments/assets/56947611-c488-453d-934c-82e67212a40c)
ONHAND03:
![image](https://github.com/user-attachments/assets/ac8c9642-2d29-4c8c-9c81-c0ea43bd6503)

ITF399P1:
![image](https://github.com/user-attachments/assets/2542cba6-34c4-43cc-bf05-d7838c563437)

**Comment by AshsubM** [comment] 2024-11-22 11:12
Closed as Completed

**Closed** 2024-11-22 11:12 UTC
Labels: bug, ADS-Ingestion, ADS, To check
