### ISSUE TITLE
Enhancement - Partitioning & Bucketing after ingestion

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#42] opened 2024-01-11 09:44 UTC
Partitioning & Bucketing after ingestion is required as there are high chances of tuning the query/indexing during the business testing and review. Expecting the similar option in ADS.

**Comment by kilam005** [comment] 2024-01-22 09:01
This is internally addressed already and its is expected to roll out in 3.1.8_xxxxx version. Lets us disccus again after the release.
@ashoksri0  / @ClementJosh21 keep @suseela22  and team updated on the availability once released

**Comment by ClementJosh21** [comment] 2024-01-29 02:19
@kilam005 We completed this as an enhancement request and is available in the 2024.01.x.

**Comment by Udhayanila8** [comment] 2024-01-29 06:57
Able to run the partition and bucketing after ingestion.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/09af486e-971b-4aa8-8fd1-fcc5b598c176)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e8cf35c4-bf01-49f3-b031-ec8fc153b3ab)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/dc43bcde-7103-40d6-bc3c-d56419069d82)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/701a1dda-6a47-481d-949b-c474d12e5c4a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f7239c1e-5081-470d-9963-261a24a64c61)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6a824687-9009-44c9-ba71-8f0ab59759a1)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/0b8661a2-784f-4b20-9a60-43b528e5eaab)

**Comment by kilam005** [comment] 2024-01-31 09:26
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by kilam005** [comment] 2024-03-08 18:03
@suseela22 

The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment] 2024-03-15 07:06
Working as expected

**Closed** 2024-03-15 07:21 UTC
Labels: enhancement, 3.1.7-issue, ADS-Ingestion, ADS, Verified, Awaiting closure
