### ISSUE TITLE
Enhancement - Retention

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#43] opened 2024-01-11 09:47 UTC
For Fixed Date retention, previous date will be useful for our trial runs which will reduce our waiting time

**Comment by kilam005** [comment] 2024-01-22 09:03
This is internally addressed already and its is expected to roll out in 3.1.8_xxxxx version. 
The working is confirmed and the need is met.

@prabhakaranUI / @ClementJosh21  inform @suseela22 and team once released

**Comment by prabhakaranUI** [comment] 2024-01-29 12:34
For fixed date retention, Users can able to select the previous date 


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/8fed3f50-1a11-43e0-bdf8-c90dfbe6098e)

**Comment by kilam005** [comment] 2024-01-29 14:21
`Fix details`
the team was under the impression the policy created will always have a date from the future, so a validation was put in place to restrict dates in the past. The fix was made to remove this unwanted validation.

**Comment by kilam005** [comment] 2024-01-31 09:27
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by Udhayanila8** [comment] 2024-02-01 12:20
Application level, able to view the previous date.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d6a89150-51e2-4270-ab82-27f8c4fdbe31)
**But unable to create the policy using the previous date, it throws an error.**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f40dc518-0afc-4307-bcbe-9772f4277b2b)
**Also in the application compliance tab, settings -> application compliance -> create policy
Unable to view the previous date it self.**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/22821c4c-b03c-4c12-af2e-8977262b1b1a)

**Comment by kilam005** [comment] 2024-02-01 12:30
@ClementJosh21 awaiting backend fix.
This is now assigned to you. Please update after fix.

**Comment by ClementJosh21** [comment] 2024-02-01 14:48
@kilam005 The fix just got merged in 2024.01.x and will be validated by testing team once it is deployed.

**Comment by Udhayanila8** [comment] 2024-02-07 10:01
Issue fixed. Tested in 146 server.
Application level 
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d8cead00-bd11-4ec2-98f2-7ffe388ff951)
Table level create a policy with an expired date
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a1739e32-32c7-4b32-9366-4fc6dee213e4)
Record level select the expired policy
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/edee7b49-ca33-4ebc-8993-794f519cd367)
From settings -> application compliance tab
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/40089e35-0f57-4b55-95a7-5874f70e6f33)
From the Job management page select the expired policy
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a09fbe97-66fa-4059-8565-a4a999a563bb)
Able to apply the expired policy
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/95ca6f86-02b3-4634-8f7f-4ebba4c7c5b2)

**Comment by kilam005** [comment] 2024-03-08 18:01
@suseela22 

The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by kilam005** [comment] 2024-03-08 18:02
`RCA`
Requirment was misunderstood and coding was employed to block all past days

`Fix details`
the understanding was corrected and the necessary code changes in both UI and BE side was made.

**Closed** 2024-03-15 07:19 UTC
Labels: 3.1.7-issue, ADS, Verified, Info Provided, Awaiting closure
