### ISSUE TITLE
CSV ingestion - Data Type Error (csv ingestion)

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#33] opened 2024-01-02 07:26 UTC
During csv ingestion we are facing issue on the below datatypes. If the metadata has double and integer datatype the ingestion is failing.

**Double Datatype**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/baa02b2e-bf05-4bf9-abe0-b2df2db89ea3)
**Integer Datatype**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/223e1f78-47e4-42fa-aab5-df51ada51530)

**Comment by VikramSelvadurai** [comment] 2024-01-24 12:13
Fix Provided: Integer and Double data type added for CSV typ ingestion and, added Condition for Integer data type 

Double data Type : 
![Screenshot from 2024-01-24 17-05-43](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/90201281/031d0a1e-ca0b-4efb-b1b4-974103c53fa6)
![Screenshot from 2024-01-24 17-06-09](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/90201281/efbb1943-e209-4438-b899-ddd81c2196bd)
CSV: 
[FND_DOC 1.csv](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/14037664/FND_DOC.1.csv)

Integer Data Type: 
![Screenshot from 2024-01-24 17-19-39](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/90201281/bbe8a971-11f7-40a8-959a-4c72fffbd3ea)
![Screenshot from 2024-01-24 17-41-40](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/90201281/1ca23182-3a20-4fe3-a348-6a53c181497c)

CSV: 
[Tabel2.csv](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/14038040/Tabel2.csv)

**Comment by ClementJosh21** [comment] 2024-01-29 02:16
@kilam005 The datatype mentioned above was missed and hence throws this error, we have handled these datatype in the enum.

**Comment by Udhayanila8** [comment] 2024-01-29 07:24
Ingestion completed for integer and double datatypes, Tested in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/965ec0b8-5401-4392-981d-94f81a4dea30)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/85d10ed7-891e-47f2-aaf8-395582405204)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f7e5a193-90e4-4f33-8a55-cf8bb48aabd4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5d1df258-e7f8-49b2-9a32-10c0416e3baa)

**Comment by kilam005** [comment] 2024-03-08 17:56
The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment] 2024-03-15 07:04
Working as expected

**Closed** 2024-03-15 07:20 UTC
Labels: 3.1.7-issue, ADS-Ingestion, ADS, Verified, Info Provided, Awaiting closure
