### ISSUE TITLE
ADS and P360-Record counts doesnt match

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#132] opened 2024-09-25 03:07 UTC
**Describe the bug**
ADS and P360 search result count does not match .This scenario is inconsistent.We have to manually clear the search Cache from ADS and P360 searches to resolve the issue

**To Reproduce**
1. In P360 ,Through patient look up .Go to vitals and measures search . record count is 10
2. Run the same query on ADS .The record count is 245 which is expected(refer attachments)
3.Clear cache from both ADS and P360 search(vitals and measures)
4.Now ,P360 matches the record count of 245.

**This behaviour is also reported by the client but the scenario is inconsistent.**
Attachments:
[error.docx](https://github.com/user-attachments/files/17123998/error.docx)

**Expected behavior**
Row counts should match .User should not achieve it by clearing the cache

**Additional context**
Build no :
Region :
Client :

**Comment by kilam005** [comment] 2024-09-25 05:16
@ThulasiP3 
Please add screen shots to understand this issue better and also include details of the product version.

**Comment by ThulasiP3** [comment] 2024-09-25 06:16
ADS version - 2024.08.45507_RC6
P360 version - 2024.08.45510

**Comment by VikramSelvadurai** [comment] 2024-09-27 10:13
Server SS: 
![image](https://github.com/user-attachments/assets/8d736d5f-1f28-4a4f-b7db-c466e20e60e1)
![image](https://github.com/user-attachments/assets/f0e95eca-f8e9-4777-bc07-7fe4a2d54592)

**Comment by kilam005** [comment] 2024-09-28 08:40
@P3IND0167 
Please test and once confirmed to work fine, add the verified and Awaiting release tags

**Comment by P3IND0167** [comment] 2024-09-28 09:08
Ok @kilam005 

Validated in test server , adding screenshots for reference

**P360**
![image](https://github.com/user-attachments/assets/2b6edacd-f4c8-43fd-9637-ee8c27ee9219)
![image](https://github.com/user-attachments/assets/cedc0c8b-df7b-43a5-8b3e-bc52d13a67d3)

Patient lookup screen
![image](https://github.com/user-attachments/assets/8ef2d50c-cc1a-436c-a936-441d6ab9becf)

**ADS Side Screenshot Reference**

![image](https://github.com/user-attachments/assets/9c03deb4-3ee1-4b6a-ba8b-12481e0cbe88)
![image](https://github.com/user-attachments/assets/55778ec5-a0b5-4d56-b138-251d82fce39b)

**Comment by kilam005** [comment] 2024-10-05 00:30
The issue is addressed in the latest build (P360 v2024.09.45555)
Link to the build shared on email on Sep 30. 
If you have not received the email, kindly reach out to support team for build details. 

Please udpate your environment with this build and verify.

**Comment by kilam005** [comment] 2024-10-05 00:30
@ThulasiP3 

The issue is addressed in the latest build (P360 v2024.09.45555)
Link to the build shared on email on Sep 30.
If you have not received the email, kindly reach out to support team for build details.

Please udpate your environment with this build and verify.

**Comment by kilam005** [comment] 2024-10-10 16:45
@ThulasiP3 
Its been more than 10 days since we gave the release.
Please validate the fix and provide a closure.
if no repsonse / concerns is received  by 18th October this issue will be auto closed taking testing team's verifiied confirmation

**Comment by ThulasiP3** [comment] 2024-10-14 05:54
Hi,

Requested for deployment in Fairview .We will validate and post back ASAP.

Thanks,
Thulasi.

**Comment by kilam005** [comment] 2024-10-14 06:07
@ThulasiP3 
For P360 we dont own the region and we never deploy.
The details about the instalation and upgrade are provided with the package.
Please update, check and confirm and provide the closure.

Like previous mentioned if no closure or concern is raised before 18th October, this will get auto closed

**Comment by kilam005** [comment] 2024-10-20 04:29
@ThulasiP3 
Reminder: Issue will be autoclosed if no action is taken on 21st Oct

**Comment by ThulasiP3** [comment] 2024-10-21 10:01
Build verified.. Unable to see the issue being replicated now.

**Comment by kilam005** [comment] 2024-10-22 02:54
Closing based on above commment

**Closed by kilam005** 2024-10-22 02:54 UTC
Labels: bug, ADS, Verified, Info Provided, Awaiting closure, P360, 18th October - auto close
