### ISSUE TITLE
Enhancement - UI change in Search to differentiate primary and nested searche

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#38] opened 2024-01-11 09:32 UTC
Need a tag/icon in UI to differentiate primary and nested searches

**Comment by ClementJosh21** [comment] 2024-01-29 02:18
@kilam005 We have added a new icon to represent whether a search is a nested/ a primary search.

**Comment by SivaMahendran17** [comment] 2024-01-29 13:02
## 192.168.56.146 (Rented Test)
For differentiating the nested and normal search the icon has been added in the above mentioned region and working as expected and attached the screenshot for reference.

**Screenshot:**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/124030288/8a473f59-637c-4b16-bf32-6dd4ccb8b267)

**Comment by kilam005** [comment] 2024-01-31 09:47
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by kilam005** [comment] 2024-03-08 17:59
@suseela22 

The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment] 2024-03-15 07:07
Working as expected

**Closed** 2024-03-15 07:21 UTC
Labels: enhancement, ADS-Search, ADS, Verified, Awaiting closure
