### ISSUE TITLE
UI - Loading issue

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#32] opened 2023-11-17 12:07 UTC
When the application tile is clicked, UI is loading for very long time and giving bad request error as below. 
server : http://192.168.1.218:4081

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/0f59331b-b1b4-42e4-9629-5c436c1b06c1)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/c0fe205f-6c0a-4b55-9795-6b1b83ce149e)

**Comment by kilam005** [comment] 2023-12-18 04:56
@Udhayanila8 please validate and assign to the necessary developers if its a bug. Please add details.

**Comment by Udhayanila8** [comment] 2023-12-18 06:01
Tested in the test region (146 server).
Able to open without getting any error. Working as expected.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e8beffba-f811-47b1-9b67-800078f4cb7a)

**Comment by suseela22** [comment] 2023-12-19 08:02
We are facing this issue again. Load is failing while clicking on the application 
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/96876df0-fb5d-40b5-9691-f1d4b7e4ee38)

**Comment by suseela22** [comment] 2024-01-03 06:29
Our team is facing the loading issue many times. Every time we got the update from product team is that the restart was done due to the ecosystem issue. Is it because of configuration? May I know the root cause for this?

Search screen update is not happening for any of the application

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/6f5a3beb-578d-4f0b-b4f3-3463d579e936)

**Comment by kilam005** [comment] 2024-01-25 02:37
@Udhayanila8 please recheck once again

**Comment by suseela22** [comment] 2024-01-30 10:35
We could not able to run any of the searches. Please keep us informed if any deployment is going on 192.168.1.218 server. 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/d0d1b4eb-a683-4d3d-a1bf-7a2ea99ffd8a)

**Comment by kilam005** [comment] 2024-01-30 13:47
This may not be due to deployment.  Also deployment to the server will not be made without prior notice.
Based on the message Its due to Sharding. Maximum shards are open.
Forwarding to team for verification and rectification.

**Comment by kilam005** [comment] 2024-02-07 09:25
@ashoksri0 has confirmed the existance of bug and has provided code fixes. More info will be provioded after testing.

**Comment by kilam005** [comment] 2024-03-27 09:04
@suseela22 
please check and provide closure for this issue

**Comment by suseela22** [comment] 2024-03-27 11:33
The issue still persists. We are facing the below error while performing the Adhoc and advance search. It is not occurring every time but randomly.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/55b8841d-3325-4d75-b5a7-2f4fa1c740a7)

**Comment by kilam005** [comment] 2024-04-03 09:22
@suseela22 please recheck and if re occurs please inform replication steps

**Comment by suseela22** [comment] 2024-04-18 07:59
Since it doesn't occurs in specific scenario and occurs randomly in different pages, I could not able to provide replication steps. Will provide detailed steps if it occurs again. 
The sharding issue still occurs while fetching the search result. As per your previous comment the fix is provided and deployed in 218 server or waiting for the fix?

**Comment by kilam005** [comment] 2024-04-18 15:28
@suseela22 
will recheck with team and update here.
Kindly hold on for a week.

**Comment by kilam005** [comment] 2024-05-08 09:24
@suseela22 

The fixes are available in 218 server.
The build version details are v2024.03.45414
please check and update us on your findings.

**Comment by kilam005** [comment] 2024-05-29 11:36
@suseela22, Please try once and provide your finding

**Comment by suseela22** [comment] 2024-05-30 09:46
Issue still persist in 218 region with  **Version: 2024.03.45414_P1**

I tried the Adhoc Search with the enduser login and the below issue occurs

**Note:** I tried with same input, after sometimes it worked.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/29b9bb9b-eea3-4a80-af81-571a80a8d3a8)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/b263ca08-800d-44f6-9f27-09a1ae953a4c)

**Comment by ClementJosh21** [comment] 2024-06-05 06:17
@kilam005 I think there is already an [issue](https://github.com/P3-Core-Dev-Team/P3-Q-A/issues/102) being tracked for the above mentioned scenario. Should be hold two issues for same scenario?

**Comment by kilam005** [comment] 2024-06-05 10:39
@suseela22 
the original issue seems to be fixed and the recently reported timeout issue is being tracker in #102 which make this a duplicate.

Can we close the issue here if the original issue is rectrified and continue the time out issue in tne 102 issue page.

**Closed** 2024-06-07 08:13 UTC
Labels: ADS-Search, ADS, 218 region, Awaiting closure
