### ISSUE TITLE
Enhancement - Ingestion Tracker

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#41] opened 2024-01-11 09:39 UTC
Filter based on **STATUS** is required in ingestion tracker

**Comment by kilam005** [comment] 2024-01-22 08:58
The status monitoring page is being revised. 
The filter option if included in the new revised page planned to get rolled out soon.
see below image for reference and upcoming changes

![Status Monitoring](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/d8f0a234-de06-417a-8639-12969d9cb5cf)

**Comment by Udhayanila8** [comment] 2024-01-29 06:18
The job status filter is available in the status monitoring page. Tested in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/42a85235-0773-4256-af22-20dfc4fb9c13)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/fa509fe4-22d0-4abc-b4fa-0e580fd54206)

**Comment by kilam005** [comment] 2024-01-31 09:26
This is planned to be avaialable in version 2024.01.x

**Comment by kilam005** [comment] 2024-03-08 18:00
@suseela22 
The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment] 2024-03-15 07:07
Working as expected

**Closed** 2024-03-15 07:22 UTC
Labels: enhancement, ADS, Verified, Awaiting closure
